"""The 4 tools AskIT can use  (used in Day 5, Day 6 and the later labs).

You do NOT edit this file. Read it: it shows exactly what the model is told about each tool.

A tool has TWO parts:
  1. a normal Python function  (does the real work)
  2. a "spec" = name + plain-English description + the inputs it needs.
     The spec is the ONLY thing the model sees. The model never sees the Python code.

All data is the fictional Orbit Corp helpdesk data (askit_data folder).
The two "write" tools (update_ticket, reset_password) are MOCKS: they change nothing on disk.
"""
import os

from askit_core.data import load_kb, load_tickets, load_users

# Notes added with update_ticket live only in memory (they disappear when the program ends).
NOTES = {}


# ---------------------------------------------------------------------------------------------
# TOOL 1: search_kb  (READ tool)  - find help-desk articles that match some words
# ---------------------------------------------------------------------------------------------
def search_kb(query):
    """Search the IT knowledge base. Returns the 3 best matching articles."""
    words = [w for w in query.lower().replace("?", " ").replace(",", " ").split() if len(w) > 2]
    scored = []
    for doc_id, text in load_kb().items():
        body = text.lower()
        title = body.split("\n")[0]                       # first line = "# Title"
        score = sum(1 for w in words if w in body) + 2 * sum(1 for w in words if w in title)
        if score > 0:
            scored.append((score, doc_id, text))
    scored.sort(key=lambda s: -s[0])                      # best match first
    results = [{"id": doc_id, "text": text[:600]} for _, doc_id, text in scored[:3]]
    if not results:
        return {"results": [], "message": "No matching article found."}
    return {"results": results}


# ---------------------------------------------------------------------------------------------
# TOOL 2: get_ticket  (READ tool)  - look up one ticket by its id
# ---------------------------------------------------------------------------------------------
def get_ticket(ticket_id):
    """Get one ticket (subject, description, priority, status, notes) by its id, e.g. TKT-0004."""
    # FAILURE SWITCH (Day 6, Lab 6B): pretend the ticket database is down.
    if os.getenv("ASKIT_TOOLS_DOWN"):
        raise RuntimeError("Ticket database is down")
    # INCIDENT SWITCH: the trainer can turn this on during the "agent stuck in a loop" incident.
    if os.getenv("ASKIT_INCIDENT", "").lower() == "loop":
        return {"ticket_id": ticket_id, "status": "SYNCING",
                "message": "The ticket system is still syncing. Please call get_ticket again."}
    for t in load_tickets():
        if t["ticket_id"].lower() == str(ticket_id).strip().lower():
            return {"ticket_id": t["ticket_id"], "user_id": t["user_id"], "subject": t["subject"],
                    "description": t["description"], "category": t["category"], "priority": t["priority"],
                    "status": t["status"], "notes": NOTES.get(t["ticket_id"], [])}
    return {"error": f"Ticket {ticket_id} not found."}


# ---------------------------------------------------------------------------------------------
# TOOL 3: update_ticket  (WRITE tool, MOCK)  - add a work note to a ticket
# ---------------------------------------------------------------------------------------------
def update_ticket(ticket_id, note):
    """Add a work note to a ticket."""
    if "error" in _find_ticket(ticket_id):
        return {"error": f"Ticket {ticket_id} not found."}
    NOTES.setdefault(ticket_id, []).append(note)
    return {"ok": True, "ticket_id": ticket_id, "notes_on_ticket": len(NOTES[ticket_id])}


# ---------------------------------------------------------------------------------------------
# TOOL 4: reset_password  (WRITE tool, MOCK)  - reset a user's password
# ---------------------------------------------------------------------------------------------
def reset_password(user_id):
    """Reset the password of an employee (mock: nothing is really reset)."""
    for u in load_users():
        if u["user_id"].lower() == str(user_id).strip().lower():
            return {"ok": True, "message": f"A temporary password was sent to the registered mobile of {u['name']}."}
    return {"error": f"User {user_id} not found."}


def _find_ticket(ticket_id):
    for t in load_tickets():
        if t["ticket_id"].lower() == str(ticket_id).strip().lower():
            return t
    return {"error": "not found"}


# ---------------------------------------------------------------------------------------------
# The two things the agent code needs:
# ---------------------------------------------------------------------------------------------
# TOOLS: tool name -> Python function. When the model says "call get_ticket", we look it up here.
TOOLS = {
    "search_kb": search_kb,
    "get_ticket": get_ticket,
    "update_ticket": update_ticket,
    "reset_password": reset_password,
}


def _spec(name, description, props, required):
    """Build one tool spec in the shape the AWS Bedrock Converse API expects."""
    return {"toolSpec": {"name": name, "description": description,
                         "inputSchema": {"json": {"type": "object", "properties": props, "required": required}}}}


# TOOL_SPECS: what the model is told. Good descriptions = the model picks the right tool.
TOOL_SPECS = [
    _spec("search_kb", "Search the IT knowledge base for how-to articles and policies (VPN, passwords, laptops, SLAs...).",
          {"query": {"type": "string", "description": "A few keywords, e.g. 'vpn error 809'"}}, ["query"]),
    _spec("get_ticket", "Look up one helpdesk ticket by its id, e.g. TKT-0004. Returns subject, priority, status and notes.",
          {"ticket_id": {"type": "string", "description": "Ticket id like TKT-0004"}}, ["ticket_id"]),
    _spec("update_ticket", "Add a work note to a ticket. This CHANGES data.",
          {"ticket_id": {"type": "string", "description": "Ticket id like TKT-0004"},
           "note": {"type": "string", "description": "The note text"}}, ["ticket_id", "note"]),
    _spec("reset_password", "Reset an employee's password. This CHANGES data.",
          {"user_id": {"type": "string", "description": "Employee id like EMP-1021"}}, ["user_id"]),
]
