"""model_factory.py  --  gives you a LangChain chat model.   >>> YOU DO NOT EDIT THIS FILE <<<

get_model() returns the first model that works:
   1. AWS Bedrock  (small Amazon Nova model from BEDROCK_SMALL_MODEL_ID in your course .env)   MAIN
   2. OpenAI       (if OPENAI_API_KEY is set in .env)                                         BACKUP
   3. Offline      (no keys: a tiny rule-based stand-in so the labs still run)               LAST RESORT
Force one with a line in .env:   ASKIT_MODEL=bedrock   or   ASKIT_MODEL=openai   or   ASKIT_MODEL=offline
"""
import json
import os
import re
import sys
import time
from pathlib import Path

try:                                                # let the Windows terminal print emoji safely
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[3]          # the Participants folder (where .env lives)
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv                      # noqa: E402

load_dotenv(ROOT / ".env")

from langchain_core.language_models.chat_models import BaseChatModel                 # noqa: E402
from langchain_core.messages import AIMessage, AIMessageChunk, HumanMessage, ToolMessage   # noqa: E402
from langchain_core.outputs import ChatGeneration, ChatGenerationChunk, ChatResult   # noqa: E402


def bedrock_ready():
    model = os.getenv("BEDROCK_SMALL_MODEL_ID", "")
    if not model or model == "REPLACE_ME":
        return False
    try:
        import boto3
        return boto3.Session().get_credentials() is not None
    except Exception:
        return False


def provider_name():
    forced = os.getenv("ASKIT_MODEL", "").strip().lower()
    if forced in ("bedrock", "openai", "offline"):
        return forced
    if bedrock_ready():
        return "bedrock"
    if os.getenv("OPENAI_API_KEY"):
        return "openai"
    return "offline"


def get_model():
    """Return a LangChain chat model (the thing you give to create_agent)."""
    name = provider_name()
    if name == "bedrock":
        from langchain_aws import ChatBedrockConverse          # LangChain's wrapper around the Converse API
        return ChatBedrockConverse(model=os.getenv("BEDROCK_SMALL_MODEL_ID"), region_name=os.getenv("AWS_REGION", "us-east-1"),
                                   temperature=0, max_tokens=800)
    if name == "openai":
        from langchain_openai import ChatOpenAI
        return ChatOpenAI(model=os.getenv("OPENAI_MODEL", "gpt-5-mini"))
    return OfflineChatModel()


def model_label():
    name = provider_name()
    return {"bedrock": os.getenv("BEDROCK_SMALL_MODEL_ID", ""), "openai": os.getenv("OPENAI_MODEL", "gpt-5-mini")}.get(name, "offline-stand-in")


# ---------------------------------------------------------------------------------------------
# Offline stand-in: NOT a real model. A few if-statements that behave like one, so the labs run without keys.
# ---------------------------------------------------------------------------------------------
class OfflineChatModel(BaseChatModel):
    delay: float = 0.03                                 # a tiny pause per word so streaming is visible

    @property
    def _llm_type(self):
        return "askit-offline"

    def bind_tools(self, tools, **kwargs):              # create_agent calls this; the stand-in ignores it
        return self

    # ---- the "thinking" ----
    def _reply(self, messages):
        n = len(messages)
        last = messages[-1]
        if isinstance(last, ToolMessage):                           # we just got a tool result
            data = _as_dict(last.content)
            if data.get("status") == "SYNCING":                     # the incident: retry the same call
                prev = [m for m in messages if isinstance(m, AIMessage) and m.tool_calls][-1].tool_calls[0]
                return _call(prev["name"], prev["args"], n)
            return AIMessage(content=_summary(data))
        question = next(m.content for m in messages if isinstance(m, HumanMessage))
        question = question if isinstance(question, str) else str(question)
        ticket = re.search(r"TKT-\d+", question, re.I)
        user = re.search(r"EMP-\d+", question, re.I)
        q = question.lower()
        if "reset" in q and user:
            return _call("reset_password", {"user_id": user.group(0).upper()}, n)
        if ticket and "note" in q:
            return _call("update_ticket", {"ticket_id": ticket.group(0).upper(), "note": "Note added by AskIT"}, n)
        if ticket:
            return _call("get_ticket", {"ticket_id": ticket.group(0).upper()}, n)
        return _call("search_kb", {"query": question}, n)

    def _generate(self, messages, stop=None, run_manager=None, **kwargs):
        return ChatResult(generations=[ChatGeneration(message=self._reply(messages))])

    def _stream(self, messages, stop=None, run_manager=None, **kwargs):
        reply = self._reply(messages)
        if reply.tool_calls:                                        # a tool request arrives in one piece
            yield ChatGenerationChunk(message=AIMessageChunk(content="", tool_call_chunks=[
                {"name": t["name"], "args": json.dumps(t["args"]), "id": t["id"], "index": 0} for t in reply.tool_calls]))
        else:                                                       # the answer arrives word by word
            for word in reply.content.split(" "):
                time.sleep(self.delay)
                yield ChatGenerationChunk(message=AIMessageChunk(content=word + " "))


def _call(name, args, n):
    """An AI message that asks for a tool. The id must be unique, so we use the message count."""
    return AIMessage(content="", tool_calls=[{"name": name, "args": args, "id": f"off{n}", "type": "tool_call"}])


def _as_dict(content):
    try:
        data = json.loads(content) if isinstance(content, str) else content
        return data if isinstance(data, dict) else {"result": data}
    except Exception:
        return {"error": str(content)}


def _summary(data):
    if "error" in data:
        return "Sorry, that did not work: " + str(data["error"])
    if data.get("results"):
        top = data["results"][0]
        return f"Best match [{top['id']}]: " + " ".join(top["text"].split())[:220]
    if "subject" in data:
        return f"Ticket {data['ticket_id']} ({data['subject']}) is {data['status']}, priority {data['priority']}."
    if data.get("ok"):
        return data.get("message") or "Done. The ticket was updated."
    return "I could not find anything useful for that."
