"""provider.py  --  talks to the AI model.   >>> YOU DO NOT EDIT THIS FILE <<<

One function matters to you:   ask_model(messages)
   - you give it the conversation so far (a list of messages)
   - it gives back the model's reply in the AWS Bedrock *Converse* format

Which model answers?  (it picks the first one that works)
   1. AWS Bedrock  - the small Amazon Nova model from BEDROCK_SMALL_MODEL_ID in your course .env   (MAIN)
   2. OpenAI       - if OPENAI_API_KEY is set in your .env                                          (BACKUP)
   3. Offline      - no keys needed: a tiny rule-based stand-in so the labs still run               (LAST RESORT)
Force one with a line in your .env file:   ASKIT_MODEL=bedrock   or   ASKIT_MODEL=openai   or   ASKIT_MODEL=offline

Whatever model answers, YOUR code always sees the same Converse-shaped reply, so you learn ONE format.
"""
import json
import os
import re
import sys
from pathlib import Path

try:                                                # let the Windows terminal print emoji and accents safely
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[3]          # the Participants folder (where .env lives)
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv                      # noqa: E402

load_dotenv(ROOT / ".env")

from askit_core.tools import TOOL_SPECS             # noqa: E402

OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5-mini")

# Prices in USD per 1 million tokens: (input, output). Prices change: verify on the provider's pricing page.
PRICES = {
    "nova-micro": (0.035, 0.14),
    "nova-lite": (0.06, 0.24),
    "gpt-5-mini": (0.25, 2.00),
}


def cost_usd(model_id, tokens_in, tokens_out):
    """Rough cost of one question. Matches the model id against the price table above."""
    for key, (p_in, p_out) in PRICES.items():
        if key in model_id:
            return tokens_in / 1e6 * p_in + tokens_out / 1e6 * p_out
    return 0.0


# ---------------------------------------------------------------------------------------------
# Which provider are we using?
# ---------------------------------------------------------------------------------------------
def bedrock_ready():
    """True when AWS keys and a Bedrock model id are available."""
    model = os.getenv("BEDROCK_SMALL_MODEL_ID", "")
    if not model or model == "REPLACE_ME":
        return False
    try:
        import boto3
        return boto3.Session().get_credentials() is not None
    except Exception:
        return False


def provider_name():
    forced = os.getenv("ASKIT_MODEL", "").strip().lower()
    if forced in ("bedrock", "openai", "offline"):
        return forced
    if bedrock_ready():
        return "bedrock"
    if os.getenv("OPENAI_API_KEY"):
        return "openai"
    return "offline"


def model_id():
    name = provider_name()
    if name == "bedrock":
        return os.getenv("BEDROCK_SMALL_MODEL_ID", "")
    if name == "openai":
        return OPENAI_MODEL
    return "offline-stand-in"


# ---------------------------------------------------------------------------------------------
# The one function you use
# ---------------------------------------------------------------------------------------------
def ask_model(messages, system=None, tools=None):
    """Send the conversation to the model. Returns the Converse-shaped reply:
         {"output": {"message": {"role": "assistant", "content": [ {"text": ...} or {"toolUse": ...} ]}},
          "stopReason": "end_turn" | "tool_use",
          "usage": {"inputTokens": n, "outputTokens": n}}
    """
    if system is None:
        from agent import SYSTEM_PROMPT            # the system prompt lives in agent.py
        system = SYSTEM_PROMPT
    tools = TOOL_SPECS if tools is None else tools
    name = provider_name()
    try:
        if name == "bedrock":
            return _bedrock(messages, system, tools)
        if name == "openai":
            return _openai(messages, system, tools)
    except Exception as e:                          # a friendly message instead of a 40-line traceback
        raise SystemExit(f"\nThe {name} model call failed: {str(e)[:300]}\n"
                         "What to try: wait 30 s (throttling) and retry, or add  ASKIT_MODEL=openai  to .env "
                         "(with OPENAI_API_KEY), or  ASKIT_MODEL=offline  to run without a model.")
    return _offline(messages)


# ---------------------------------------------------------------------------------------------
# 1. AWS Bedrock - the Converse API  (this is the AWS step of Session 5)
# ---------------------------------------------------------------------------------------------
_client = None


def _bedrock(messages, system, tools):
    global _client
    import boto3
    from botocore.config import Config
    if _client is None:
        _client = boto3.client("bedrock-runtime", region_name=os.getenv("AWS_REGION", "us-east-1"),
                               config=Config(retries={"max_attempts": 8, "mode": "adaptive"},
                                             read_timeout=120, connect_timeout=10))
    resp = _client.converse(
        modelId=os.getenv("BEDROCK_SMALL_MODEL_ID"),
        system=[{"text": system}],
        messages=messages,                                   # already in Converse format - no conversion
        toolConfig={"tools": tools},                         # the tool specs from askit_core/tools.py
        inferenceConfig={"maxTokens": 800, "temperature": 0},
    )
    return resp


# ---------------------------------------------------------------------------------------------
# 2. OpenAI (backup) - convert our Converse messages to OpenAI format and back
# ---------------------------------------------------------------------------------------------
def to_openai_messages(system, messages):
    out = [{"role": "system", "content": system}]
    for m in messages:
        if m["role"] == "user":
            for b in m["content"]:
                if "toolResult" in b:                        # a tool result becomes a "tool" message
                    r = b["toolResult"]
                    out.append({"role": "tool", "tool_call_id": r["toolUseId"],
                                "content": json.dumps(r["content"][0]["json"])})
            texts = [b["text"] for b in m["content"] if "text" in b]
            if texts:
                out.append({"role": "user", "content": "\n".join(texts)})
        else:                                                # assistant: text and/or tool calls
            text = "".join(b.get("text", "") for b in m["content"])
            msg = {"role": "assistant", "content": text or None}
            calls = [b["toolUse"] for b in m["content"] if "toolUse" in b]
            if calls:
                msg["tool_calls"] = [{"id": c["toolUseId"], "type": "function",
                                      "function": {"name": c["name"], "arguments": json.dumps(c["input"])}}
                                     for c in calls]
            out.append(msg)
    return out


def to_openai_tools(tools):
    return [{"type": "function", "function": {"name": t["toolSpec"]["name"],
                                              "description": t["toolSpec"]["description"],
                                              "parameters": t["toolSpec"]["inputSchema"]["json"]}} for t in tools]


def from_openai_response(resp):
    """OpenAI reply -> Converse-shaped reply."""
    msg = resp.choices[0].message
    content = []
    if msg.content:
        content.append({"text": msg.content})
    for c in (msg.tool_calls or []):
        content.append({"toolUse": {"toolUseId": c.id, "name": c.function.name,
                                    "input": json.loads(c.function.arguments or "{}")}})
    return {"output": {"message": {"role": "assistant", "content": content}},
            "stopReason": "tool_use" if msg.tool_calls else "end_turn",
            "usage": {"inputTokens": resp.usage.prompt_tokens, "outputTokens": resp.usage.completion_tokens}}


def _openai(messages, system, tools):
    from openai import OpenAI
    kwargs = dict(model=OPENAI_MODEL, messages=to_openai_messages(system, messages), tools=to_openai_tools(tools))
    if OPENAI_MODEL.startswith("gpt-5"):
        kwargs["reasoning_effort"] = "minimal"               # keep the "thinking" short and cheap
    return from_openai_response(OpenAI().chat.completions.create(**kwargs))


# ---------------------------------------------------------------------------------------------
# 3. Offline stand-in - NOT a real model. A few if-statements that act like one, so labs run without keys.
# ---------------------------------------------------------------------------------------------
def _reply(blocks, tin, tout):
    uses = any("toolUse" in b for b in blocks)
    return {"output": {"message": {"role": "assistant", "content": blocks}},
            "stopReason": "tool_use" if uses else "end_turn",
            "usage": {"inputTokens": tin, "outputTokens": tout}}


def _offline(messages):
    size = len(json.dumps(messages)) // 4
    last = messages[-1]["content"]
    results = [b["toolResult"] for b in last if "toolResult" in b]
    if results:                                              # we just got a tool result -> answer, or retry if syncing
        data = results[0]["content"][0]["json"]
        if data.get("status") == "SYNCING":                  # the incident: "please call get_ticket again"
            prev = [b["toolUse"] for b in messages[-2]["content"] if "toolUse" in b][0]
            return _reply([{"toolUse": {"toolUseId": f"off{len(messages)}", "name": prev["name"],
                                        "input": prev["input"]}}], size, 20)
        return _reply([{"text": _summary(data)}], size, 40)
    question = messages[0]["content"][0]["text"]
    ticket = re.search(r"TKT-\d+", question, re.I)
    user = re.search(r"EMP-\d+", question, re.I)
    q = question.lower()
    if "reset" in q and user:
        call = ("reset_password", {"user_id": user.group(0).upper()})
    elif ticket and "note" in q:
        call = ("update_ticket", {"ticket_id": ticket.group(0).upper(), "note": "Note added by AskIT: " + question[:80]})
    elif ticket:
        call = ("get_ticket", {"ticket_id": ticket.group(0).upper()})
    else:
        call = ("search_kb", {"query": question})
    return _reply([{"toolUse": {"toolUseId": f"off{len(messages)}", "name": call[0], "input": call[1]}}], size, 20)


def _summary(data):
    if "error" in data:
        return "Sorry, that did not work: " + data["error"]
    if data.get("results"):
        top = data["results"][0]
        return f"Best match [{top['id']}]: " + " ".join(top["text"].split())[:220]
    if "subject" in data:
        return f"Ticket {data['ticket_id']} ({data['subject']}) is {data['status']}, priority {data['priority']}."
    if data.get("ok"):
        return data.get("message") or "Done. The ticket was updated."
    return "I could not find anything useful for that."
